

services:
  frontend:
    build:
      context: ./greenX-assessment-tool-frontend
      dockerfile: Dockerfile
    container_name: Greenx_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./greenX-assessment-tool-frontend:/app  # Ensure correct syntax with a dash (-)
      - node_modules:/app/node_modules  # This volume stores node_modules
    networks:
      - greenx-network

  backend:
    build:
      context: ./GreenX_DCS_Assesment_Tool_Backend
      dockerfile: Dockerfile
    container_name: Greenx_backend
    ports:
      - "8000:8000"
    volumes:
      - ./GreenX_DCS_Assesment_Tool_Backend:/app
    networks:
      - greenx-network
    depends_on:
      - greenx-db

  greenx-db:
    image: mysql:latest
    container_name: greenx-db
    environment:
      MYSQL_ROOT_PASSWORD: umarfarooq
      MYSQL_DATABASE: mysql
    volumes:
      - myvolume:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - greenx-network

networks:
  greenx-network:
    driver: bridge

volumes:
  myvolume:  # Volume for MySQL data persistence
  node_modules:  # Volume for frontend node_modules

